export default () => [
  { id: 0, name: "animals", platformId: 2 },
  { id: 1, name: "beard", platformId: 2 },
  { id: 2, name: "business", platformId: 2 },
  { id: 3, name: "cars", platformId: 2 },
  { id: 4, name: "city", platformId: 2 },
  { id: 5, name: "flowers", platformId: 2 },
  { id: 6, name: "food", platformId: 1 },
  { id: 7, name: "nature", platformId: 1 },
  { id: 8, name: "people", platformId: 1 },
  { id: 9, name: "sports", platformId: 1 },
  { id: 10, name: "tech", platformId: 1 },
  { id: 11, name: "travel", platformId: 1 },
  { id: 12, name: "water", platformId: 1 },
];
